/*
Is new status Valid */
:PAR1 = '' ;
SELECT :$.@ INTO :PAR1 FROM DUMMY ;
SELECT :$1.@ INTO :$.@
FROM DUMMY
WHERE :$.@ NOT IN (
SELECT STATDES FROM ZCLA_NEXTCONTSTAT
WHERE CONTRACT = :$.CONTRACT
);
ERRMSG 899 WHERE :$.@ NOT IN (
SELECT STATDES FROM ZCLA_NEXTCONTSTAT
WHERE CONTRACT = :$.CONTRACT
);
