ERRMSG 800 WHERE EXISTS (
SELECT 'X'
FROM PROJACTS
WHERE 0=0
AND   DOC = :$$$.DOC
AND   WBS = :$.WBS
);
SELECT 'H' , SQL.GUID
INTO :$.EDITTYPE , :$.GUID
FROM DUMMY
WHERE :$.GUID = '' ;
/*
*/
SELECT -1 INTO :$.STATDES 
WHERE :STATDES = 0 ;
LABEL 30092412 ;
