/*ZLIA_PDV_DEFOPT/DEVTYPENAME/CHOOSE-FIELD*/
SELECT STRCAT('O/C:',OC.BSEN_NAME,' | RCD:',RCD.BSEN_NAME), 
PDV.DEVTYPENAME, PDV.DEVTYPEID 
FROM ZLIA_PDV_CONFIG PDV, ZLIA_PDV_BSENS OC, 
ZLIA_PDV_BSENS RCD
WHERE PDV.OC_BSEN_ID = OC.BSEN_ID
AND PDV.RCD_BSEN_ID = RCD.BSEN_ID
AND PDV.DEVTYPEID <> 0
ORDER BY PDV.DEVTYPEID;
