/**/
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'OWNER/CHECK-FIELD' , SQL.USER
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE;
/*
Changed? */
GOTO 99 WHERE EXISTS(
SELECT 'x'
FROM DUMMY
WHERE :$.OWNER = :$1.OWNER
);
/**/
#INCLUDE ZCLA_FIXACT/ZCLA_FORMVAR
#INCLUDE ZCLA_FIXACT/ZCLA_BUF2
#INCLUDE func/ZCLA_THROWERR
LABEL 99 ;
