/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/POST-INSERT'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/* 
Get for variables */
#INCLUDE ZCLA_ELACT/ZCLA_FORMVAR
/*
Update the element rooms and components */
#INCLUDE ZCLA_ELACT/ZCLA_BUF1
/*
Calculate points */
#INCLUDE ZCLA_ELACT/ZCLA_BUF4
