/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/POST-INSERT'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
:ELEMENT = 0 ;
SELECT :$.PROJACT INTO :ELEMENT
FROM DUMMY ;
/*
Update the element rooms and components */
:OPENEDIT = 0 ;
#INCLUDE ZCLA_ELACT/ZCLA_BUF1
/*
Calculate points */
#INCLUDE ZCLA_ELACT/RECALC
/*
Update Status */
INSERT INTO ZCLA_ELACTSTAT (PROJACT , OWNER , STEPSTATUS)
SELECT :$.PROJACT , SQL.USER , -1
FROM DUMMY ;
    