/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/ZCLA_POST-UPDATE'
FROM DUMMY WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
:ELEMENT = 0 ;
SELECT :$.PROJACT INTO :ELEMENT
FROM DUMMY ;
#INCLUDE ZCLA_ELACT/RECALC
/*
Update Status */
:ID = 0 ;
SELECT ELACT INTO :ID
FROM ZCLA_ELACTSTAT
WHERE PROJACT = :$.PROJACT ;
:LOADNAME = 'STATUSMAILZCLA_EL' ;
#INCLUDE STATUSTYPES/ZCLA_BUF1
/* 
Create Questionnaire fix ready */
#INCLUDE ZCLA_ELACT/ZCLA_BUF16 
