/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/POST-INSERT'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/*
Calculate points */
#INCLUDE ZCLA_ELACT/ZCLA_FORMVAR
#INCLUDE ZCLA_ELACT/ZCLA_BUF4
