:DT = 03/06/23 00:00 ;
LABEL 10 ; 
:MIN = :MAX = :TD = 0 ;
SELECT :DT + 1439 INTO :TD
FROM DUMMY ;

SELECT MIN(UDATE) INTO :MIN
FROM UPGNOTES
WHERE USER = SQL.USER
AND UDATE BETWEEN :DT AND :TD
FORMAT ;
SELECT MAX(UDATE) INTO :MAX
FROM UPGNOTES
WHERE USER = SQL.USER
AND UDATE BETWEEN :DT AND :TD
FORMAT ;
SELECT :DT, 0.0 +(:MAX - :MIN) / 60 AS HOURS
FROM DUMMY FORMAT ;
SELECT :DT + 1440 INTO :DT
FROM DUMMY ;
LOOP 10 WHERE :DT <= SQL.DATE ;
