/*LOGPART/ZLIA_PDV_DEFDES/CHOOSE-FIELD */
SELECT CO.DEVTYPENAME, DV.PDV_DEFDES, DV.PDV_DEFID
FROM ZLIA_PDV_DEFOPT DV, ZLIA_PDV_CONFIG CO
WHERE DV.DEVTYPEID = CO.DEVTYPEID
AND DV.PDV_DEFID <> 0
ORDER BY DV.PDV_DEFID;
