/* Copy FROM project TO customer
*/
:DOC = 0 ;
SELECT DOCUMENTS.CUST INTO :DOC
FROM ZCLA_HOUSETYPE , DOCUMENTS
WHERE 0=0
AND   ZCLA_HOUSETYPE.DOC = DOCUMENTS.DOC
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :$.HS
;
/* Check exists
 */
:DOCNO = '' ;
SELECT STRCAT(CUSTDES, ' core types') INTO :DOCNO 
FROM CUSTOMERS
WHERE CUST = :DOC ;
SELECT :$.NA2 , :DOCNO 
INTO :PAR1, :PAR2
FROM DUMMY ;
ERRMSG 800 WHERE EXISTS (
SELECT 'x'
FROM ZCLA_HOUSETYPE
WHERE 0=0
AND   DOC = :DOC
AND   TYPENAME = :$.NA2
);
SELECT :DOC
FROM DUMMY
FORMAT ADDTO '../ZCLA_COPYHOUSE.txt'
;
SELECT SQL.TMPFILE
INTO :GEN FROM DUMMY ;
LINK GENERALLOAD TO :GEN ;
ERRMSG 1 WHERE :RETVAL = 0
;
/*
*/
:LN = 0 ;
/* insert Proj line */
SELECT MAX(LINE) + 1 INTO :LN FROM GENERALLOAD;
INSERT INTO GENERALLOAD (LINE , RECORDTYPE, KEY1)
SELECT :LN , '1' , ITOA(:DOC)
FROM DUMMY
;
SELECT MAX(LINE) + 1 INTO :LN FROM GENERALLOAD ;
INSERT INTO GENERALLOAD (LINE , RECORDTYPE
, INT1, INT2, INT3
, CHAR1 , CHAR2 , TEXT1, TEXT2 , DATE1 , INT10 , CHAR3 )
SELECT :LN ,   '2'
,   :DOC
,   EL
,   COL
,   '¬'
,   ''
,   :$.NA2
,   :$.DE2
,   SQL.DATE
,   HOUSETYPEID
,   'Y'
FROM ZCLA_HOUSETYPE
WHERE 0=0
AND   HOUSETYPEID  = :$.HS
;
DELETE FROM ERRMSGS
WHERE 0=0
AND   USER = SQL.USER
AND   TYPE = 'i'
;
EXECUTE INTERFACE 'ZCLA_COPYTOCORE', SQL.TMPFILE, '-L', :GEN
;
:i_LOGGEDBY = 'ZCLA_COPYHOUSE';
#INCLUDE func/ZEMG_ERRMSGLOG
SELECT LINE, RECORDTYPE , KEY1 , LOADED , INT1, INT2, INT3, INT4 ,
CHAR1 , CHAR2 , TEXT1, TEXT2
FROM GENERALLOAD
FORMAT ADDTO '../ZCLA_COPYHOUSE.txt'
;
SELECT * FROM ERRMSGS
WHERE 0=0
AND   USER = SQL.USER
AND   TYPE = 'i'
FORMAT ADDTO '../ZCLA_COPYHOUSE.txt'
;
UNLINK GENERALLOAD ;
