/* 
*/
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_FIXACT/POST-UPDATE'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
#INCLUDE ZCLA_FIXACT/ZCLA_FORMVAR
/*
Raise Questionnaire Task*/
#INCLUDE ZCLA_FIXACT/ZCLA_BUF3 
/*
*/
UPDATE PROJACTS
SET ZCLA_DOREFRESH = 'Y'
WHERE PROJACT = :ELEMENT ;