:S = 0.0 ;
SELECT :$.@ INTO :S
FROM DUMMY
;
GOSUB 100 WHERE :S < 0 ;
SELECT (:S / :$$.PACKAGEPRICE) * 100 INTO :$.SPLIT
FROM DUMMY ;
SUB 100 ;
SELECT :$$.PACKAGEPRICE - SUM( VALUE ) INTO :S
FROM ZCLA_ELEDITSPLIT
WHERE 0=0
AND   EDITID = :$.EDITID
AND   FIXID <> :$.FIXID
;
SELECT :S INTO :$.VALUE
FROM DUMMY ;
RETURN ;
