:S = 0.0 ;
SELECT :$.@ INTO :S
FROM DUMMY
;
GOSUB 100 WHERE :S < 0 ;
SELECT :$$.PACKAGEPRICE * (:S / 100) INTO :$.VALUE
FROM DUMMY ;
SUB 100 ;
SELECT 100 - SUM(SPLIT) INTO :S
FROM ZCLA_HTEDITSPLIT
WHERE 0=0
AND   EDITID = :$.EDITID
AND   FIXID <> :$.FIXID
;
SELECT :S INTO :$.SPLIT
FROM DUMMY ;
RETURN ;
