/*ZLIA_CUDB_DEFOPT/RCD_PDV_DEFDES/POST-FIELD */
SELECT PDV_DEFID INTO :$.RCD_PDV_DEFOPT
FROM ZLIA_PDV_DEFOPT
WHERE 0=0
AND PDV_DEFDES = :$.@;
/*Update CHAR Key*/
SELECT ITOA(PDV_DEFID) INTO :$.RCD_PDV_CHAR
FROM ZLIA_PDV_DEFOPT
WHERE 0=0
AND PDV_DEFDES = :$.@;
