/* Determine blank part */
:BLANKPART = 0;
SELECT PART
INTO :BLANKPART
FROM PART
WHERE ZCLA_CUNITBLANK = 'Y'
;
/* Get Families */
:FAM_CU  = :FAM_CIRC = :FAM_INHERIT = 0 ;
SELECT 0 + FAMILY INTO :FAM_CU 
FROM FAMILY
WHERE FAMILYNAME = 'CONSUMER UNITS'
;
SELECT 0 + FAMILY INTO :FAM_CIRC 
FROM FAMILY
WHERE FAMILYNAME = 'C/Unit - Circuits'
;
SELECT 0 + FAMILY INTO :FAM_INHERIT 
FROM FAMILY
WHERE FAMILYNAME = '_Part_Mfr_Inherited'
;