/* 
Create Plot change log */
:OPENEDIT = 0 ;
SELECT EDITID INTO :OPENEDIT
FROM ZCLA_ELEDIT
WHERE 0=0
AND   PROJACT = :$.PROJACT
AND   CLOSEFLAG <> 'Y'
;
INSERT INTO ZCLA_ELEDITLOG ( EDITID
,      PROJACT
,      UPDTYPE
,      EDITTYPE
,      GUID
,      FIELD
)
SELECT EDITID
,      :$.PROJACT
,      :UPDTYPE
,      :$.EDITTYPE
,      :$.GUID
,      :FIELD
FROM ZCLA_ELEDIT
WHERE 0=0
AND   PROJACT = :$.PROJACT
AND   CLOSEFLAG <> 'Y'
;