/*
Skip if interface */
GOTO 999 WHERE :FORM_INTERFACE = 1 ;
/*
Debug */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_PLOTATTR/PRE-FORM'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
#INCLUDE ZCLA_FIXACT/ZCLA_FORMVAR
/*
*/
:ACTIVATE_POST_FORM = 'Y' ;
/* 
Populate default plot attributes on the form */
INSERT INTO ZCLA_PLOTATTR ( PROJACT , CHARID )
SELECT :ELEMENT , CHARID
FROM ZCLA_PLOTCHARS
WHERE 0=0
AND   ZCLA_PLOTCHARS.INACTIVE <> 'Y' ;
/*
*/
LABEL 999 ;