/*
:HOUSETYPE = 2 ;
:DOC = 4 ;
Update fix uplift by HOUSETYPE
*/
:FIXID = 0 ;
:FIXUPLIFT = 0.0 ;
/* Reset Values */
UPDATE ZCLA_HOUSETYPEFIX SET
ZCLA_FIXUPLIFT = 1
WHERE 0=0
AND   ZCLA_HOUSETYPEFIX.HOUSETYPEID = :HOUSETYPE
;
/*
*/
DECLARE @FIX89 CURSOR FOR
SELECT ZCLA_HOUSETYPEFIX.FIXID, ZCLA_FIXES.FIXUPLIFT
FROM  ZCLA_FIXES , ZCLA_HOUSETYPEFIX
WHERE 0=0
AND   ZCLA_FIXES.FIXID = ZCLA_HOUSETYPEFIX.FIXID
AND   ZCLA_HOUSETYPEFIX.HOUSETYPEID  = :HOUSETYPE
;
OPEN @FIX89 ;
GOTO 9999 WHERE :RETVAL = 0 ;
LABEL 5009;
FETCH @FIX89 INTO :FIXID , :FIXUPLIFT ;
GOTO 6009 WHERE :RETVAL = 0 ;
/*
*/
UPDATE ZCLA_HOUSETYPEFIX SET
ZCLA_FIXUPLIFT = ( :FIXUPLIFT <> 0 ? 1 + ( :FIXUPLIFT / 100 ) : 1 )
WHERE 0=0
AND   ZCLA_HOUSETYPEFIX.FIXID = :FIXID
AND   ZCLA_HOUSETYPEFIX.HOUSETYPEID = :HOUSETYPE
;
/*
*/
LOOP 5009 ;
LABEL 6009 ;
CLOSE @FIX89 ;
LABEL 9999 ;
