/*
Skip if interface */
GOTO 999 WHERE :FORM_INTERFACE = 1 ;
/* 
*/
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_PLOTCU/PRE-FORM'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
#INCLUDE ZCLA_FIXACT/ZCLA_FORMVAR
/*
*/
:ACTIVATE_POST_FORM = 'Y' ;
LABEL 999 ;