/* Skip if not interface
*/
GOTO 999 WHERE :FORM_INTERFACE <> 1
;
/* Skip if not ZCLA_COPY  = 'Y'
*/
GOTO 999 WHERE NOT EXISTS(
SELECT 'x'
FROM ZCLA_HOUSETYPE
WHERE 0=0
AND HOUSETYPEID = :$.HOUSETYPEID
AND ZCLA_COPY  = 'Y'
);
/* Generate Missing Fixes 
*/
INSERT INTO ZCLA_HOUSETYPEFIX
(HOUSETYPEID , FIXID)
SELECT :HOUSETYPE , FIXID
FROM ZCLA_FIXES
WHERE 0=0
AND   FIX <> '-1'
AND   FIXID > 0
;
/* DELETE the house type properties
*/
DELETE FROM ZCLA_HTCHARS
WHERE HOUSETYPEID = :$.HOUSETYPEID
;
/* DELETE components
*/
DELETE FROM ZCLA_COMPONENT
WHERE COMPONENT IN (
SELECT        ZCLA_COMPONENT.COMPONENT
FROM            ZCLA_HOUSETYPE , ZCLA_ROOMS
WHERE 0=0
AND   ZCLA_HOUSETYPE.HOUSETYPEID = ZCLA_ROOMS.HOUSETYPEID
AND   ZCLA_ROOMS.ROOM = ZCLA_COMPONENT.ROOM
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :$.HOUSETYPEID
);
/* Delete rooms
*/
DELETE FROM ZCLA_ROOMS
WHERE ROOM IN (
SELECT        ZCLA_ROOMS.ROOM
FROM            ZCLA_HOUSETYPE , ZCLA_ROOMS
WHERE 0=0
AND   ZCLA_HOUSETYPE.HOUSETYPEID = ZCLA_ROOMS.HOUSETYPEID
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :$.HOUSETYPEID
);
/* Delete Consumer unit ways
*/
DELETE FROM ZCLA_CUNITCONFIG WHERE CUNITCONFIG IN (
SELECT        ZCLA_CUNITCONFIG.CUNITCONFIG
FROM            ZCLA_CUNITCONFIG, ZCLA_HOUSETYPE ,
ZCLA_CONSUMERUNITS
WHERE 0=0
AND   ZCLA_HOUSETYPE.HOUSETYPEID = ZCLA_CONSUMERUNITS.HOUSETYPEID
AND   ZCLA_CUNITCONFIG.CONSUMERUNIT =
ZCLA_CONSUMERUNITS.CONSUMERUNIT
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :$.HOUSETYPEID
);
/* Delete Consumer unit
*/
DELETE FROM ZCLA_CONSUMERUNITS WHERE CONSUMERUNIT IN (
SELECT ZCLA_CONSUMERUNITS.CONSUMERUNIT
FROM            ZCLA_HOUSETYPE , ZCLA_CONSUMERUNITS
WHERE 0=0
AND   ZCLA_HOUSETYPE.HOUSETYPEID = ZCLA_CONSUMERUNITS.HOUSETYPEID
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :$.HOUSETYPEID
);
/* Delete attachments */
DELETE FROM EXTFILES WHERE EXTFILENUM IN (
SELECT EXTFILES.EXTFILENUM
FROM   EXTFILES , ZCLA_HOUSETYPE
WHERE  0=0
AND    ZCLA_HOUSETYPE.HOUSETYPEID = EXTFILES.IV
AND    ZCLA_HOUSETYPE.HOUSETYPEID = :$.HOUSETYPEID
AND    TYPE = '¬'
);
#INCLUDE ZCLA_HOUSETYPE/POST-INSERT
LABEL 999 ;
/* Update Modifiers */
#INCLUDE ZCLA_HOUSETYPE/ZCLA_BUF2