/* Update aggregate values for the housetype
*/
:PARTCOST = :LABCOST = :MILEAGECOST = 0.0 
;
SELECT SUM( ZCLA_SUNDRY + ZCLA_PARTSUM ) 
,      SUM( ZCLA_LABTOTAL + ZCLA_TRAVEL ) - SUM( ZCLA_NEGPOINT )
,      SUM( ZCLA_MILEAGE )  
INTO :PARTCOST
,    :LABCOST
,    :MILEAGECOST
FROM ZCLA_HOUSETYPEFIX
WHERE 0=0
AND   HOUSETYPEID = :HOUSETYPE
;
UPDATE ZCLA_HOUSETYPE  
SET PARTCOST = :PARTCOST
,   LABCOST = :LABCOST
,   MILEAGECOST = :MILEAGECOST
WHERE 0=0
AND   HOUSETYPEID = :HOUSETYPE
;
/* 
Update screen values */
SELECT PARTCOST , LABCOST , MILEAGECOST , ZCLA_MISSINGREPL 
INTO :$$.PARTCOST ,    :$$.LABCOST 
,    :$$.MILEAGECOST , :$$.ZCLA_MISSINGREPL 
FROM ZCLA_HOUSETYPE
WHERE 0=0
AND   HOUSETYPEID = :HOUSETYPE
;