/*
Calculate Uplifts by HOUSETYPE */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_HOUSETYPE/ZCLA_BUF2' FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/*
*/
:ZCLA_TIMETOSITE =  0 ;
:ZCLA_MILESTOSITE = 0.0 ;
/* 
Update fix and house type modifiers */
#INCLUDE ZCLA_FIXES/ZCLA_HOUSETYPE
#INCLUDE ZCLA_CHARACTERISTIC/ZCLA_HOUSETYPE
GOTO 2550 WHERE :$$.TYPE = '¬' ;
/* 
It's a project */
:DOC = :HOUSETYPE = 0 ;
SELECT :$$.DOC , :$.HOUSETYPEID INTO :DOC , :HOUSETYPE
FROM DUMMY ;
SELECT :DOC , :HOUSETYPE FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/* 
Get site modifiers */
#INCLUDE DOCUMENTS_p/ZCLA_HOUSETYPE
#INCLUDE ZCLA_PLOTFIXUPLIFTS/ZCLA_HOUSETYPE
#INCLUDE ZCLA_SITECHARS/ZCLA_HOUSETYPE
/*
Set Travel Values for site */
SELECT ZCLA_MILESTOSITE , ZCLA_TIMETOSITE
INTO :ZCLA_MILESTOSITE , :ZCLA_TIMETOSITE
FROM DOCUMENTS
WHERE 0=0
AND   DOCUMENTS.DOC = :DOC ;
SELECT :ZCLA_MILESTOSITE , :ZCLA_TIMETOSITE FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/*
*/
GOTO 2590 ;
LABEL 2550 ;
/* 
It's a core, so set site modifiers to 1 */
UPDATE ZCLA_HOUSETYPEFIX
SET   ZCLA_NEGPOINT = 0
,     ZCLA_BRUPLIFT = 1
,     ZCLA_FIXUPLIFT = 1
WHERE 0=0
AND   ZCLA_HOUSETYPEFIX.HOUSETYPEID = :HOUSETYPE ;
LABEL 2590 ;
/* 
Calculate points */
#INCLUDE ZCLA_HOUSETYPE/ZCLA_BUF4
/* 
Refresh House totals */
#INCLUDE ZCLA_HOUSETYPE/ZCLA_BUF5