/* Set default values from the
.  housetype on insert
*/
SELECT :$$.ZCLA_HOUSETYPEID ,  ATOI( :$.ZCLA_FIXNAME )
FROM DUMMY FORMAT '../ZCLA_FIXACT-ZCLA-POST-INSERT'
;
:ZCLA_SITEUPLIFT  =  :ZCLA_FIXUPLIFT  =  :ZCLA_BRUPLIFT  =
:ZCLA_UPLIFT  =  :ZCLA_TRAVEL  =  :ZCLA_LABTOTAL  =
:ZCLA_PARTSUM  =  :ZCLA_MILEAGE  =  :ZCLA_SUNDRY  =
:ZCLA_NEGPOINT  = :MOD_HT = :MOD_ST = :MOD_PL =
:ZCLA_LABOURPOINTS = 0.0
;
SELECT ZCLA_INITPOINTS
,   ZCLA_SITEUPLIFT
,   ZCLA_FIXUPLIFT
,   ZCLA_BRUPLIFT
,   ZCLA_UPLIFT
,   ZCLA_TRAVEL
,   ZCLA_LABTOTAL
,   ZCLA_PARTSUM
,   ZCLA_MILEAGE
,   ZCLA_SUNDRY
,   ZCLA_NEGPOINT
,   ZCLA_LABOURPOINTS
,   MOD_HT
,   MOD_ST
,   1.0
FROM ZCLA_HOUSETYPEFIX
WHERE 0=0
AND   HOUSETYPEID = :$$.ZCLA_HOUSETYPEID
AND   FIXID = ATOI( :$.ZCLA_FIXNAME )
FORMAT ADDTO '../ZCLA_FIXACT-ZCLA-POST-INSERT'
;
SELECT ZCLA_INITPOINTS
,   ZCLA_SITEUPLIFT
,   ZCLA_FIXUPLIFT
,   ZCLA_BRUPLIFT
,   ZCLA_UPLIFT
,   ZCLA_TRAVEL
,   ZCLA_LABTOTAL
,   ZCLA_PARTSUM
,   ZCLA_MILEAGE
,   ZCLA_SUNDRY
,   ZCLA_NEGPOINT
,   ZCLA_LABOURPOINTS
,   MOD_HT
,   MOD_ST
,   1.0
INTO :ZCLA_INITPOINTS
,   :ZCLA_SITEUPLIFT
,   :ZCLA_FIXUPLIFT
,   :ZCLA_BRUPLIFT
,   :ZCLA_UPLIFT
,   :ZCLA_TRAVEL
,   :ZCLA_LABTOTAL
,   :ZCLA_PARTSUM
,   :ZCLA_MILEAGE
,   :ZCLA_SUNDRY
,   :ZCLA_NEGPOINT
,   :ZCLA_LABOURPOINTS
,   :MOD_HT
,   :MOD_ST
,   :MOD_PL
FROM ZCLA_HOUSETYPEFIX
WHERE 0=0
AND   HOUSETYPEID = :$$.ZCLA_HOUSETYPEID
AND   FIXID = ATOI( :$.ZCLA_FIXNAME )
;
UPDATE PROJACTS
SET ZCLA_INITPOINTS = :ZCLA_INITPOINTS
,   ZCLA_SITEUPLIFT = :ZCLA_SITEUPLIFT
,   ZCLA_FIXUPLIFT = :ZCLA_FIXUPLIFT
,   ZCLA_BRUPLIFT = :ZCLA_BRUPLIFT
,   ZCLA_UPLIFT = :ZCLA_UPLIFT
,   ZCLA_TRAVEL = :ZCLA_TRAVEL
,   ZCLA_LABTOTAL = :ZCLA_LABTOTAL
,   ZCLA_PARTSUM = :ZCLA_PARTSUM
,   ZCLA_MILEAGE = :ZCLA_MILEAGE
,   ZCLA_SUNDRY = :ZCLA_SUNDRY
,   ZCLA_NEGPOINT = :ZCLA_NEGPOINT
,   ZCLA_LABOURPOINTS = :ZCLA_LABOURPOINTS
,   MOD_HT = :MOD_HT
,   MOD_ST = :MOD_ST
,   MOD_PL = :MOD_PL
WHERE 0=0
AND   ZCLA_PLOT = :$$.PROJACT
;
