:CFGCOUNT = :TOTALWAYS = 0;
/* Select the child parts of the CUNIT components */
/* insert into bom */
SELECT PART, SON, SONQUANT
FROM ZCLA_CUNITCONFIG CFG, ZCLA_CONSUMERUNITS CU, PARTARC PA
WHERE CFG.CONSUMERUNIT = CU.CONSUMERUNIT
AND PA.PART = CFG.PART
AND CU.HOUSETYPEID = 61

FORMAT;
/* Count how many components in the cunit */
SELECT COUNT(*)
INTO :CFGCOUNT
FROM ZCLA_CUNITCONFIG CFG, ZCLA_CONSUMERUNITS CU
WHERE CFG.CONSUMERUNIT = CU.CONSUMERUNIT
AND CU.HOUSETYPEID = 61

;
/* Select total waycount from cunits */
SELECT SUM(ZCLA_CUNITWAYS)
INTO :TOTALWAYS
FROM ZCLA_CONSUMERUNITS CU, PART P
WHERE CU.HOUSETYPEID = 61
AND CU.PART = P.PART
FORMAT;
/* Number of blanks needed */
:BLANKSUM = :TOTALWAYS - :CFGCOUNT;
/* Determine blank part */
:BLANKPART = 0;
SELECT PART
INTO :BLANKPART
FROM PART
WHERE ZCLA_CUNITBLANK = 'Y'
;
/* Insert into BOM */
/*
INSERT INTO ZCLA_PARTARC
(USER, PART, SON ...
VALUES (SQL.USER, :BLANKPART
...