:LN = 0 ;
SELECT 0 + MAX(LN) INTO :LN
FROM ZCLA_STATLOG
WHERE 0=0
AND   ZCLA_STATLOG.TYPE = :$.TYPE
AND   ZCLA_STATLOG.PARENT = :$.NSCUST
;
INSERT INTO ZCLA_STATLOG ( PARENT
, LN
, TYPE
, USER
, CURDATE
, OLDSTATUSDES
, NEWSTATUSDES )
SELECT :$.NSCUST
, :LN + 1
, :$.TYPE
, SQL.USER
, SQL.DATE
, :$.STATDES1
, :$.STATDES
FROM DUMMY ;
LABEL 99 ;
