INSERT INTO ZCLA_FIXACTSTAT (PROJACT , OWNER , STEPSTATUS)
SELECT PROJACT , USER , -1
FROM PROJACTS
WHERE 0=0
AND LEVEL = 3
AND PROJACT NOT IN (
SELECT PROJACT FROM ZCLA_FIXACTSTAT
);
INSERT INTO ZCLA_ELACTSTAT (PROJACT , OWNER , STEPSTATUS)
SELECT PROJACT , USER , -1
FROM PROJACTS
WHERE 0=0
AND LEVEL = 2
AND PROJACT NOT IN (
SELECT PROJACT FROM ZCLA_ELACTSTAT
);
