:UPDTYPE = 'I' ;
:FIELD = 'INSERT'
#INCLUDE ZCLA_ELEDIT/ZCLA_BUF1
/*
*/
UPDATE ZCLA_ELEDITLOG
SET    INT1     = :$.PART
,      INT2     = :$.TQUANT
,      ROOM     = :$.ROOM
,      ROOMDES  = :$.ROOMDES
,      NEWVALUE = :$.PARTNAME
WHERE  0 = 0 
AND    PROJACT  = :$.PROJACT
AND    EDITTYPE = :$.EDITTYPE
AND    GUID     = :$.GUID
AND    UPDTYPE  = :UPDTYPE
AND    FIELD    = :FIELD
AND    EDITID   = :OPENEDIT
;