/* Select 25mm and 38mm sheathing parts */
/* 25mm sheathing */
:MM25PART = :MM38PART = 0;
SELECT PART
INTO :MM25PART
FROM PART, MNFCTR
WHERE PART.ZCLA_MANFID = MNFCTR.MNF
AND MNFNAME = '_SHEATHING'
AND ZCLA_THICKNESS = 25.0
;
/* 38mm sheathing */
SELECT PART
INTO :MM38PART
FROM PART, MNFCTR
WHERE PART.ZCLA_MANFID = MNFCTR.MNF
AND MNFNAME = '_SHEATHING'
AND ZCLA_THICKNESS = 38.0
;
