/* Update the element rooms and components
*/
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/ZCLA_BUF1' , :PLOT , :DOC
FROM DUMMY 
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
SELECT PLOT.PROJACT 
,   EL.PROJACT 
,   EL.ZCLA_HOUSETYPEID
FROM PROJACTS PLOT , PROJACTS EL
WHERE 0=0
AND   PLOT.PROJACT  = EL.ZCLA_PLOT
AND   PLOT.PROJACT  = :PLOT
AND   PLOT.DOC      = :DOC
AND   :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/*
*/
:PL = :EL = :HT = 0 ;
DECLARE @EL25 CURSOR FOR
SELECT PLOT.PROJACT 
,   EL.PROJACT 
,   EL.ZCLA_HOUSETYPEID
FROM PROJACTS PLOT , PROJACTS EL
WHERE 0=0
AND   PLOT.PROJACT  = EL.ZCLA_PLOT
AND   PLOT.PROJACT  = :PLOT
AND   PLOT.DOC      = :DOC
;
OPEN @EL25;
ERRMSG 999 WHERE :RETVAL = 0;
LABEL 1001;
FETCH @EL25 INTO :PL , :EL , :HT ;
GOTO 1008 WHERE :RETVAL = 0
;
SELECT :PL , :EL , :HT
FROM DUMMY
WHERE :DEBUG = 1
FORMAT :DEBUGFILE ;
/* Update the elements rooms
*/
INSERT INTO ZCLA_PLOTROOMS (ROOM , PROJACT , COL)
SELECT ROOM , :EL , ZCLA_ROOMS.COL
FROM ZCLA_HOUSETYPE , ZCLA_ROOMS
WHERE 0=0
AND   ZCLA_ROOMS.HOUSETYPEID = ZCLA_HOUSETYPE.HOUSETYPEID
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :HT
;
DELETE FROM ZCLA_PLOTROOMS
WHERE 0=0
AND   PROJACT = :EL
AND   ROOM NOT IN (
SELECT ROOM
FROM ZCLA_HOUSETYPE , ZCLA_ROOMS
WHERE 0=0
AND   ZCLA_ROOMS.HOUSETYPEID = ZCLA_HOUSETYPE.HOUSETYPEID
AND   ZCLA_HOUSETYPE.HOUSETYPEID = :HT
);
/* Update Room Components
*/
:ROOM = :PART = :TQUANT = :COL = 0 ;
DECLARE @EL26 CURSOR FOR
SELECT ZCLA_COMPONENT.ROOM , PART , TQUANT , ZCLA_COMPONENT.COL
FROM ZCLA_COMPONENT , ZCLA_ROOMS
WHERE 0=0
AND   ZCLA_ROOMS.ROOM = ZCLA_COMPONENT.ROOM
AND   HOUSETYPEID = :HT
;
OPEN @EL26;
GOTO 2009 WHERE :RETVAL = 0;
LABEL 2001;
FETCH @EL26 INTO :ROOM , :PART , :TQUANT , :COL ;
GOTO 2008 WHERE :RETVAL = 0
;
SELECT :ROOM , :PART , :TQUANT , :COL
FROM DUMMY 
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
GOTO 99 WHERE EXISTS (
SELECT 'x'
FROM ZCLA_PLOTCOMPONENT
WHERE 0=0
AND   PROJACT = :EL
AND   ROOM = :ROOM
AND   PART = :PART
);
/*
*/
SELECT 'Add'
FROM DUMMY 
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
INSERT INTO ZCLA_PLOTCOMPONENT
(PROJACT , ROOM , PART , TQUANT , COL)
SELECT :EL , :ROOM , :PART , :TQUANT , :COL
FROM DUMMY;
LOOP 2001;
LABEL 99 ;
/*
*/
SELECT 'Update'
FROM DUMMY 
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
UPDATE ZCLA_PLOTCOMPONENT
SET TQUANT = :TQUANT
WHERE 0=0
AND   PROJACT = :EL
AND   ROOM = :ROOM
AND   PART = :PART
;
LOOP 2001;
LABEL 2008;
CLOSE @EL26;
LABEL 2009;
/*
*/
LOOP 1001;
LABEL 1008;
CLOSE @EL25;
LABEL 1009;
