/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ELACT/POST-UPDATE' 
FROM DUMMY 
WHERE :DEBUG = 1
FORMAT :DEBUGFILE ;
/*
Skip - no change */
GOTO 999 WHERE :$.ZCLA_COL = :$1.ZCLA_COL ;
UPDATE ZCLA_PLOTROOMS
SET    COL = :$.ZCLA_COL
WHERE  0=0
AND    PROJACT = :$.PROJACT ;
UPDATE ZCLA_PLOTCOMPONENT
SET    COL = :$.ZCLA_COL
WHERE  0=0
AND    PROJACT = :$.PROJACT ;
LABEL 999 ;
#INCLUDE ZCLA_ELACT/ZCLA_BUF4
