/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_DELPLOTS/STEP30' FROM DUMMY
FORMAT ADDTO :DEBUGFILE ;
/*
*/
SELECT :$.CNF AS 'Typed'
,      :$.PRO AS 'Description'
,      :$.DOC AS 'DOC'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE
;
:PAR1 = :PAR2 = '' ;
SELECT :$.CNF , :$.PRO
INTO :PAR1 , :PAR2
FROM DUMMY ;
ERRMSG 800 WHERE :$.CNF <> :$.PRO ;
