/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_DELPLOTS/STEP10' FROM DUMMY
WHERE 0=0
AND :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
/*
*/
LINK DOCUMENTS TO :$.PAR;
ERRMSG 1 WHERE :RETVAL <= 0;
SELECT DOCUMENTS.DOC , DOCPROJ.PROJDES
INTO :$.DOC , :$.PRO
FROM DOCUMENTS , DOCPROJ
WHERE 0=0
AND   DOCUMENTS.DOC = DOCPROJ.DOC
AND   DOCUMENTS.DOC > 0
;
SELECT :$.DOC , :$.PRO
FROM DUMMY
WHERE 0=0
AND :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
UNLINK DOCUMENTS ;
