/*Sort form by WAYNO then KLINE*/

/* ZCLA_PLOTCUCFG/PARTNAME/POST-FIELD */
GOTO 999 WHERE :$.WAYNO <> 0 ;
SELECT 1 INTO :$.WAYNO FROM DUMMY ;
SELECT MAX(WAYNO) + 1 INTO :$.WAYNO FROM ZCLA_PLOTCUCFG
WHERE CONSUMERUNIT = :$$.CONSUMERUNIT;
LABEL 999;
