/* ZCLA_CUNITCONFIG/PARTNAME/CHOOSE-FIELD */

/*Modify From
SELECT PARTDES, PARTNAME
FROM PART P,  FAMILY F, ZCLA_PARTTYPE T
WHERE P.FAMILY = F.FAMILY
AND P.ZCLA_PARTTYPE = T.TYPEID
AND ZCLA_CUNITCIRCUIT = 'Y'
AND T.TYPENAME = 'C'
AND PARTNAME LIKE 'C8%'
;
*/
/*To*/
SELECT PARTDES, PARTNAME
FROM 
PART P,
ZLIA_PDV_DEFOPT OPT,
ZLIA_PDV_CONFIG CFG
WHERE 
PARTNAME LIKE 'C8%'
AND P.ZLIA_PDV_DEFID = OPT.PDV_DEFID
AND OPT.DEVTYPEID = CFG.DEVTYPEID
AND CFG.DEVTYPEID = :$.PDVSELECT
;
