GOTO 10423 WHERE NOT EXISTS(
SELECT 'x' FROM ERRMSGS
WHERE 0=0
AND   USER = SQL.USER
AND   TYPE = 'i'
);
SELECT MESSAGE INTO :PAR1
FROM ERRMSGS
WHERE 0=0
AND   USER = SQL.USER
AND   TYPE = 'i'
AND   LINE = 1
;
ERRMSG 899 ;
LABEL 10423 ;
