/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_ADDPLOTFORM/STEP5' FROM DUMMY
FORMAT ADDTO :DEBUGFILE ;
/* Get housetypes
*/
LINK DOCUMENTS TO :$.PAR;
ERRMSG 1 WHERE :RETVAL <= 0;
/*
*/
DELETE FROM ZCLA_USERHT
WHERE USER = SQL.USER
;
INSERT INTO ZCLA_USERHT (USER , DOC , HOUSETYPE)
SELECT SQL.USER , DOCUMENTS.DOC , HOUSETYPEID
FROM DOCUMENTS , ZCLA_HOUSETYPE
WHERE 0=0
AND   DOCUMENTS.DOC =  ZCLA_HOUSETYPE.DOC
AND   DOCUMENTS.DOC > 0
;
UNLINK DOCUMENTS ;
