/* */
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'ZCLA_PLOTROOMS/POST-INSERT'
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE ;
#INCLUDE ZCLA_FIXACT/ZCLA_FORMVAR
/*
*/
UPDATE PROJACTS
SET ZCLA_DOREFRESH = 'Y'
WHERE PROJACT = :ELEMENT ;
/* */
#INCLUDE PARTARC/ZCLA_ELEMREPLACE
