/**/
#INCLUDE func/ZCLA_DEBUGUSR
SELECT 'STEPSTATUSDES/CHECK-FIELD' , SQL.USER
FROM DUMMY
WHERE :DEBUG = 1
FORMAT ADDTO :DEBUGFILE;
/*
Is new status Valid */
:PAR1 = '' ;
SELECT :$.@ INTO :PAR1 FROM DUMMY ;
ERRMSG 899 WHERE :$.@ NOT IN (
SELECT STATDES FROM ZCLA_NEXTELSTAT
WHERE ELACT = :$.PROJACT
);
/*
*/
LABEL 99 ;
