/* Add Choose Field to PART for C8 Circuit default cable*/
/*LOGPART/ZLIA_CIRCCAB_DEFDES/CHOOSE-FIELD */
SELECT '', CABLEDES, CABLEID
FROM ZLIA_CAB_CONFIG
WHERE CABLEID <> 0
AND CABLEDES <> ''
ORDER BY CABLEID;
